### ISSUE TITLE
mergedales - crossxy3d.nnn.nc and surf_xy.nnn.nc empty

### ISSUE THREAD

**Issue by fjansson** [CloudResolvingClimateModeling/dalesview#3]
Mergedales seems to work for the vertical cross sections (xz, yz) byt not for the horizontal ones (xy, surf_xy).

Sample output:
```/perm/ms/nl/nkjf/dalesview/merge_grids.py --dir dales-work-35456/ --np 2
INFO:__main__:processing time step 0 of 601 for output crossxz2d.001.nc...
INFO:__main__:processing time step 0 of 601 for output crossyz2d.001.nc...
INFO:__main__:processing time step 0 of 601 for output surf_xy.001.nc...
INFO:__main__:processing time step 0 of 602 for output crossxy3d.001.nc...
INFO:__main__:processing time step 10 of 601 for output crossxz2d.001.nc...
INFO:__main__:processing time step 20 of 601 for output crossxz2d.001.nc...
INFO:__main__:processing time step 30 of 601 for output crossxz2d.001.nc...
INFO:__main__:processing time step 40 of 601 for output crossxz2d.001.nc...
...
```
surf_xy.001.nc and crossxy3d.001.nc are not processed for any time steps past 0, apparently.

**Comment by goord** [comment]
Hi Fredrik, can you point me to the output, because I can't reproduce the problem with my run data...

**Comment by fjansson** [comment]
Here: /scratch/ms/nl/nkjf/cabauwL2-04/dales-work-35456
This run has nprocx=1, nprocy=8 - maybe this triggers some problems not present in a symmetric case?

meanwhile, I found more problems - see the other issue.

**Comment by goord** [comment]
Yes well ***in theory*** it should work in the non-symmetric case, which means that if it did it would be a miracle

**Comment by goord** [comment]
Should be fixed after rev. c0b131cf46260d6481196dd74599849b680dc749

**Comment by fjansson** [comment]
Yes, it's fixed now! Closing.
