### ISSUE TITLE
merge_grids - output crossxz is too wide, crossyz2d empty

### ISSUE THREAD

**Issue by fjansson** [CloudResolvingClimateModeling/dalesview#4]
For a Dales run with a 200 x 200 grid, with nprocx=1 and nprocy=8,
crossxz seems correct, except the field is much wider, in x, than necessary. The extra part contains NaN.
The part with data is 200 cells wide as it should, the whole file is 1600 cells wide.
The other files, crossyz2d.001.nc, surf_xy.001.nc, crossxy3d.001.nc contain no time points.

Launched this way:
```
MERGEGRIDS=/perm/ms/nl/nkjf/dalesview/merge_grids.py 
cd ${PBS_O_WORKDIR}    # Take me to the directory where I launched qsub
$MERGEGRIDS --dir ./ --np 3 --chunksize 20
```
in the directory /scratch/ms/nl/nkjf/cabauwL2-04/dales-work-35456

Output:
```
INFO:__main__:processing time step 0 of 1290 for output crossxz2d.001.nc...
INFO:__main__:processing time step 0 of 1290 for output crossyz2d.001.nc...
INFO:__main__:processing time step 0 of 1290 for output surf_xy.001.nc...
INFO:__main__:processing time step 0 of 1290 for output crossxy3d.001.nc...
INFO:__main__:processing time step 20 of 1290 for output crossxz2d.001.nc...
INFO:__main__:processing time step 40 of 1290 for output crossxz2d.001.nc...
INFO:__main__:processing time step 60 of 1290 for output crossxz2d.001.nc...
...
```

Dales produces some unnecessary cross-section files e.g. crossxz.x000y001.001.nc, y002, etc. These are empty. Maybe they confuse the merging? For crossxz, only y000 files should be meged, and crossyz only x000 files.

**Comment by goord** [comment]
Should be fixed after rev. c0b131cf46260d6481196dd74599849b680dc749

**Comment by fjansson** [comment]
Yes, it's fixed now! Closing.
